---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vortex-agent
  labels:
    app: vortex-agent
spec:
  selector:
    matchLabels:
      name: vortex-agent
  template:
    metadata:
      labels:
        name: vortex-agent
    spec:
      hostPID: true
      containers:
      - name: vortex-agent
        image: asia.gcr.io/mobingi-main/vortex-agent:58de46b2-e08b-40d4-b185-fdabe977264e
        imagePullPolicy: Always
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
