---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vortex-agent
  labels:
    app: vortex-agent
spec:
  selector:
    matchLabels:
      name: vortex-agent
  template:
    metadata:
      labels:
        name: vortex-agent
    spec:
      hostPID: true
      containers:
      - name: vortex-agent
        image: asia.gcr.io/mobingi-main/vortex-agent:2f032154-771f-4cc2-9361-f0a29fde8245
        imagePullPolicy: Always
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
