---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vortex-agent
  labels:
    app: vortex-agent
spec:
  selector:
    matchLabels:
      name: vortex-agent
  template:
    metadata:
      labels:
        name: vortex-agent
    spec:
      hostPID: true
      containers:
      - name: vortex-agent
        image: asia-docker.pkg.dev/mobingi-main/asia-pub/vortex-agent:e3cc54e5-ba26-40c3-ad9f-e535908f5fcd
        imagePullPolicy: Always
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
