---
name: main

on:
  push:
    branches: [ "main" ]
    tags: ['*']
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 'Setup Go'
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: 'Setup LLVM and Clang'
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "20.1.4"

    - name: 'Build binary'
      if: startsWith(github.event.ref, 'refs/heads/')
      run: |
        ROOT_DIR=$PWD
        git clone https://github.com/cilium/ebpf
        cd ebpf/cmd/bpf2go/ && go build -v
        mkdir -p $HOME/.local/bin/ && cp bpf2go $HOME/.local/bin/
        cd $ROOT_DIR/ && go generate && make

    - name: 'Release from tags'
      if: startsWith(github.event.ref, 'refs/tags/v')
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        ROOT_DIR=$PWD
        git clone https://github.com/cilium/ebpf
        cd ebpf/cmd/bpf2go/ && go build -v
        mkdir -p $HOME/.local/bin/ && cp bpf2go $HOME/.local/bin/
        cd $ROOT_DIR/ && EXTRA_BPF2GO_CFLAGS=-DDEBUG_BPF_PRINTK=0 go generate && make
        tar czvf vortex-agent-${GITHUB_REF_NAME}-x86_64-linux.tar.gz bin/
        gh release create ${GITHUB_REF_NAME} ./*.tar.gz --generate-notes
